personalsite/pages/urls.py
from django.urls import path

from . import views

app_name = "pages"
urlpatterns = [
    path("", views.IndexView, name="index"),
    path("about", views.AboutView, name="about"),
    path("freelancing", views.FreelancingView, name="freelancing"),
    path("projects", views.ProjectsView, name="projects"),
    path("projects/<str:project_name>", views.ProjectPageView, name="project"),
]

personalsite/personalsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import Http404

urlpatterns = [
    path("", include("pages.urls")),
    path("play", include("play.urls")),
    #path('admin/', admin.site.urls),
]

# Show the 404 page when a page isn't found
handler404 = 'pages.views.Show404View'

# Handle 500, server error
handler500 = 'pages.views.Show500View'

# Handle 404, permission denied
# handler403 = 'pages.views.PermissionDeniedView'

# Handle 400, bad request
# handler400 = 'pages.views.BadRequestView'

personalsite/play/urls.py
from django.urls import path

from . import views

app_name = "play"
urlpatterns = [
    path("", views.IndexView, name="index"),
]

personalsite/pages/models.py
from django.db import models

# Create your models here.

personalsite/pages/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.urls import reverse

def IndexView(request):
    return render(request, "pages/index.html")

def AboutView(request):
    return render(request, "pages/about.html")

def FreelancingView(request):
    return render(request, "pages/freelancing.html")

def ProjectsView(request):
    return render(request, "pages/projects/projects.html")

def ProjectPageView(request, project_name):
    return render(request, "pages/projects/" + str(project_name) + ".html")

def Show404View(request, exception):
    return render(request, "pages/404.html")

def Show500View(request):
    return render(request, "pages/404.html")

personalsite/play/views.py
from django.shortcuts import render

def IndexView(request):
    return render(request, "play/index.html")

personalsite/pages/templates/pages/about.html
{% extends "pages/default.html" %}

{% load static %}

{% block title %}About{% endblock %}

{% block content %}

<font face="Helvetica" color="#444" size="3">
    My drive to enter software development began with my passion for gaming. I was inspired by many games I played growing up that left an impact on me. Some of these games include <i>Super Mario World</i>, <i>Donkey Kong Country</i>, <i>The Legend of Zelda: Link's Awakening</i>, and <i>Kirby's Dream Land</i>. The unique worlds and characters they presented kept me engaged and entertained for hours and fueled my imagination. By becoming a developer, I wanted to return the favor and provide the magic of games to the new generation so they could be engaged and inspired just as I was in my youth.
    <br />
    <br />
    My favorite types of game genres are platformer, RPG, and puzzle. I play Super Smash Bros. and Super Smash Bros. Melee competitively, and I love reading about how my favorite games were made via developer interviews. Additionally, I enjoy doing game research for <a target="_blank" href="https://tcrf.net/The_Cutting_Room_Floor">TCRF</a>, which I occasionally <a target="_blank" href="https://tcrf.net/Special:Contributions/Kimimaru">contribute to</a>.
    <br />
    <br />
    Since 2019, I've become a free software advocate and developer after a revelation; upon realizing that, despite how much software can empower us, many choose to use it to undermine our liberties and rights for control and/or profit. Many people, including myself, have been conditioned to throw away their right to privacy for the sake of convenience using software. I've learned that these two things are not mutually exclusive, and I believe that free software is the only way to ensure a free society and live in a world where software respects our rights as human beings rather than data subjects.
    <br />
    <br />
    I have contributed to several free software projects, such as the <a target="_blank" href="https://github.com/MonoGame/MonoGame">MonoGame framework</a>, <a target="_blank" href="https://github.com/libretro/RetroArch">RetroArch</a> frontend, the <a target="_blank" href="https://github.com/linuxmint/cinnamon">Cinnamon GNU/Linux desktop environment</a>, <a target="_blank" href="https://kde.org/">KDE</a>, and many others. I've also <a target="_blank" href="https://media.libreplanet.org/u/libreplanet/m/empowering-community-oriented-play-with-trbot/">done talks on free software</a> at events like LibrePlanet. All of my new projects will be free software, and I plan to continue working on more prominent free software projects in the future. You can find many of my own projects on this site and on <a target="_blank" href="https://codeberg.org/kimimaru/">Codeberg</a>.
    <br />
    <br />
    I hope you enjoy your stay, and feel free to explore my work. If you'd like to contact me for any reason, including business inquiries, don't hesitate to reach out through any of the platforms at the footer of the page.
    <br />
    <br />
</font>

{% endblock %}

personalsite/pages/templates/pages/default.html
<!DOCTYPE html>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pages/main.css' %}">

<head>
	<title>{% block title %} Title {% endblock %}</title>
</head>
<body>
    <h2><font face="Helvetica" color="#666">Thomas Deeb, Software Developer</font></h2>
    <hr />
	<nav>
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'pages:projects' %}">Projects</a></li>
            <li><a target="_blank" href="{% static 'Resume.pdf' %}">Resume</a></li>
            <li><a href="{% url 'pages:about' %}">About</a></li>
        </ul>
	</nav>
    <hr />
	<div class="container">
	
	{% block content %}Content{% endblock %}
	
	</div>
	<footer>
        <ul>
            <li><a href="mailto:tdd ( * at * ) posteo (DOT ('.')) us">email</a></li>
            <li><a href="https://matrix.to/#/@kimimaru:matrix.org">Matrix</a></li>
            <li><a href="https://codeberg.org/kimimaru">Codeberg</a></li>
        </ul>
        <div class="license-footer">
            This website was developed in Django and is licensed under the terms of the <a class="license-footer" href="https://creativecommons.org/licenses/by-nd/4.0/">Creative Commons Attribution-No Derivative Works 4.0 license (or a later version)</a>. All thoughts expressed on this page are my own. This website is hosted on green energy.
        </div>
	</footer>
</body>

personalsite/pages/templates/pages/freelancing.html
{% extends "pages/default.html" %}

{% load static %}

{% block title %}Freelancing{% endblock %}

{% block content %}

<font face="Helvetica" color="#555">
    <h2>Freelancing Services</h2>
    I offer freelance application and game development services through <a target="_blank" href="https://www.upwork.com/freelancers/~013785e9318a21c619">Upwork</a>. I can work in C#, Unity, MonoGame, mobile, VR, and much more. Some of my work includes:
    <ul>
        <li>Wrote code for Spatial Digital to create avatars with realistic movements for a mobile fashion app.</li>
        <li>UX improvements for Cosmo's Tuxedo on <a target="_blank" href="https://store.steampowered.com/app/1377280/Electioneering">Electioneering</a>.</li>
        <li>Performance optimization and new features of a virtual recreation of the historic Deepdene estate for TJC Heritage LTD.</li>
    </ul>
    For more details, review my work history and portfolio on my Upwork profile. I focus on good communication to ensure my work meets your expectations. I'm happy to negotiate my rates - if you'd like to enlist my services, please contact me via email or invite me to interview for your job on Upwork.
</font>

{% endblock %}

personalsite/pages/templates/pages/index.html
{% extends "pages/default.html" %}

{% load static %}

{% block title %}Thomas Deeb, Free Software Advocate and Developer{% endblock %}

{% block content %}

<div class="blurb">
    <font face="Helvetica" color="#555">
        <h2>Home</h2>
        <div class="grid-container" style="display:grid; grid-template-columns: auto auto auto auto; padding: 10px; grid-gap: 10px 10px; justify-content: space-around">
            <div class="grid-item">
                <a target="_self" href="{% url 'pages:project' 'trbot' %}">
                    <img class="noborder nofit" src="{% static 'pages/images/TRBot/TRBotLogo.png' %}" width="320" height="233">
                </a>
            </div>
            <div class="grid-item">
                <a target="_self" href="{% url 'pages:project' 'mazeburrow' %}">
                    <img src="{% static 'pages/images/MazeBurrow/MazeBurrow-LevelComplete.png' %}" width="320" height="233">
                </a>
            </div>
            <div class="grid-item">
                <a target="_self" href="{% url 'pages:project' 'yousician' %}">
                    <img src="{% static 'pages/images/Yousician/yousician-logo.jpg' %}" width="320" height="233">
                </a>
            </div>
        </div>
        <br />
        Welcome to my personal site! I'm a free/libre software developer with 10+ years of experience writing code of all kinds. I find delight in empowering people with tools and experiences to enhance their lives.
        <br />
        <br />
        I'm an advocate of <a href="https://www.gnu.org/philosophy/free-sw.html">Free Software</a> and strongly believe that it is a requirement for a free society in the digital age we live in. Insisting on free software asserts that people have the right to study, improve on works, and share their knowledge with others. We must take action now to secure a future where technology empowers us rather than restricts and controls us. Open standards, free software, and raising awareness are the stepping stones towards such a future.
        <br />
        <br />
        However you arrived at this site, I hope you enjoy your stay! You can <a href="{% url 'pages:about' %}">learn more about me</a> or view my <a href="{% url 'pages:projects' %}">portfolio</a>, which includes my professional experience.
        <br />
        <br />
        For business inquiries, please contact me at <!-- EmailDiv -->tdd <!--GIBBERISH--> [ AT ] <!--Niin?!-->posteo<!-- NiinNo--> [ DOT ] <!--Who is this example@email.com? -->us<!--This is an email form SPAM!-->.
        <br />
        <br />
    </font>
</div>

{% endblock %}

personalsite/pages/templates/pages/project.html
{% extends "pages/default.html" %}
{% block content %}
<font face="Helvetica" color="#555">
    <h2>{% block ptitle %}Title{% endblock %}</h2>
    <h4>Technologies: {% block technologies %}Technologies{% endblock %}</h4>
    {% block pcontent %}Content{% endblock %}
</font>
{% endblock %}

personalsite/pages/templates/pages/projects/blueapprentice.html
{% extends "pages/project.html" %}

{% load static %}

{% block title %}Blue Apprentice{% endblock %}
{% block ptitle %}Blue Apprentice{% endblock %}
{% block technologies %}C#, Unity, Git{% endblock %}

{% block pcontent %}

Blue Apprentice is an educational science game made by Galxyz (pronounced "Galaxies") designed for elementary school students. Blue Apprentice is unique in that it seamlessly weaves educational elements into all aspects of the game, down to the gameplay itself. For example, to solve puzzles you will need to combine elements from the Periodic Table to craft new items that allow you to progress.
<br />
<br />
This game was built in Unity and was already very large when I joined. I was initially fixing bugs until I got familiar with the codebase, after which I moved onto adding new features, such as costume painting. This feature allowed the player to draw on their character's outfit using an assortment of patterns and colors to modify the outfit's appearance at runtime. If the player liked what they drew, they can save it into a custom outfit slot and make their character wear it at any time.
<br />
<br />
<b>Trailer</b>
<br/>
<iframe width='640' height='360' src='https://yewtu.be/embed/OrsXC5gTL4o' style='border:none;'></iframe>
<br />
<br />
<a target="_blank" href="https://itunes.apple.com/us/app/blue-apprentice/id1123707853">
<img class="noborder" src="{% static 'pages/images/BlueApprentice/scimage.png' %}" width="160" height="54" />
</a>
<a target="_blank" href='https://play.google.com/store/apps/details?id=com.galxyz.ba'>
<img class="noborder" alt='Get it on Google Play' src="{% static 'pages/images/BlueApprentice/scimage1.png' %}" width="188" height="56" />
</a>

{% endblock %}

personalsite/pages/templates/pages/projects/darblez.html
{% extends "pages/project.html" %}

{% load static %}

{% block title %}Darblez{% endblock %}
{% block ptitle %}Darblez{% endblock %}
{% block technologies %}C#, Unity, NGUI, Git{% endblock %}

{% block pcontent %}

Darblez is a competitive head-to-head mobile game created by LG Dev Shop and released on iOS and Android on February 17, 2016.
<br />
<br />
This was the first professional project I've worked on. For this role, I was a Software Engineer for over a year, using Unity's scene editor and NGUI to design scenes and menus for the game, such as the Inventory and Credits. I gained a lot of experience communicating with servers by sending and receiving JSON data, and I wrote C# scripts to implement gameplay and UI features in addition to fixing bugs.
<br />
<br />
<b> Gameplay Video</b>
<br />
<iframe width='640' height='360' src='https://yewtu.be/embed/lQ4oHv8JSQI' style='border:none;'></iframe>
<br />
<br />

{% endblock %}

personalsite/pages/templates/pages/projects/defendyourfort.html
{% extends "pages/project.html" %}

{% load static %}

{% block title %}Defend Your Fort{% endblock %}
{% block ptitle %}Defend Your Fort{% endblock %}
{% block technologies %}C#, MonoGame, XAML, Adobe Photoshop, Adobe Illustrator, Git{% endblock %}

{% block pcontent %}

Defend Your Fort is a defense game for Windows 8 and Windows Phone 8 in which you must defend your fort from the Goblin tribe. To defeat a Goblin, the player must tap or click on the Goblin's location on-screen. There are three weapons for the player to use, each being more effective at killing certain types of Goblins than others. After each level, the player enters a shop where he/she can purchase upgrades for the fort, helpers that aid in defense, or repairs if the fort took any damage. This game was heavily inspired by the classic game, Defend Your Castle, by XGen Studios.
<br />
<br />
I worked on this game for two months with my brother using C# and the MonoGame framework. I coded the base engine, implemented AI for the helpers, and created a large chunk of the art assets including the fort, flying goblins, and title screen font. Defend Your Fort was released on the Windows Store on November 19, 2014.
<br />
<br />
Click on the image below to view Defend Your Fort on the Windows Store.
<br />
<br />
<a target="_blank" href="http://apps.microsoft.com/windows/en-us/app/defend-your-fort/375e7914-f7c6-43bf-a72c-5754e9c157e1">
    <img src="{% static 'pages/images/DYF/dyftitlescreen.png' %}" width="360" height="240">
</a>

{% endblock %}

personalsite/pages/templates/pages/projects/epicubed.html
{% extends "pages/project.html" %}

{% load static %}

{% block title %}Epicubed{% endblock %}
{% block ptitle %}Epicubed{% endblock %}
{% block technologies %}C#, Unity, Jira, Git{% endblock %}

{% block pcontent %}

Epicubed is a 3D puzzle-platformer in which the player takes control of cubes and records their actions through time. The goal of each level is to get the Hero Cube to the Goal Door. There are various types of cubes with special abilities, including the Gravity Cube, which can briefly hover in the air, and the Spring Cube, which launches other cubes that land on it upwards like a spring.
<br />
<br />
Epicubed was my final project in the Senior Game Design series at UC Santa Cruz. I was part of a team of four known as Astral Studios. Epicubed was built in the Unity engine, with scripts coded in C#. I designed all of the game's 24 levels, implemented the different types of cubes, ran playtesting sessions, and fixed gameplay-related bugs. To facilitate designing levels, we used the ProBuilder and ProGrids plugins; these plugins enabled us to scale levels consistently with the size of the cubes the player controls.
<br />
<br />
We used Git for revision control and Agile-Scrum for handling milestones and releases. Instructors regularly checked on our progress and offered advice and feedback.
<br />
<br />
<a target="_blank" href="{% static 'pages/images/Epicubed/titlescreen.png' %}">
    <img src="{% static 'pages/images/Epicubed/titlescreen.png' %}" width="400" height="225">
</a>
<h2>Showcase</h2>
<div class="grid-container" style="display:grid; grid-template-columns: 160px 160px 160px 160px; padding: 10px; grid-gap: 10px 10px; justify-content: space-between">
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/titlescreen.png' %}">
            <img src="{% static 'pages/images/Epicubed/titlescreen.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/world-1-select.png' %}">
            <img src="{% static 'pages/images/Epicubed/world-1-select.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/level-preview.png' %}">
            <img src="{% static 'pages/images/Epicubed/level-preview.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/third-person-cube.png' %}">
            <img src="{% static 'pages/images/Epicubed/third-person-cube.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/gravity-cube.png' %}">
            <img src="{% static 'pages/images/Epicubed/gravity-cube.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/level-complete.png' %}">
            <img src="{% static 'pages/images/Epicubed/level-complete.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/world-1-level.png' %}">
            <img src="{% static 'pages/images/Epicubed/world-1-level.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/world-2-level.png' %}">
            <img src="{% static 'pages/images/Epicubed/world-2-level.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/world-2-select.png' %}">
            <img src="{% static 'pages/images/Epicubed/world-2-select.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/world-3-select.png' %}">
            <img src="{% static 'pages/images/Epicubed/world-3-select.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/world-3.png' %}">
            <img src="{% static 'pages/images/Epicubed/world-3.png' %}" width="160" height="160">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Epicubed/world-4-teleport-cubes.png' %}">
            <img src="{% static 'pages/images/Epicubed/world-4-teleport-cubes.png' %}" width="160" height="160">
        </a>
    </div>
</div>

{% endblock %}

personalsite/pages/templates/pages/projects/hypernet.html
{% extends "pages/project.html" %}

{% load static %}

{% block title %}Hypernet Arena{% endblock %}
{% block ptitle %}Hypernet Arena{% endblock %}
{% block technologies %}C#, Unity, PlayFab, Git{% endblock %}

{% block pcontent %}

Hypernet Arena is a fast-paced competitive top-down shooter for the web by <a target="_blank" href="https://boom.tv">Boom.tv</a>. The quick pace allows Twitch streamers to easily finish a 1000+ man tournament in approximately 10 minutes. This makes it very appealing, as streamers can take a short break from their normal schedule while further engaging with their viewers. Tournaments can be organized via a separate client given to the streamers, which also allows them to spectate individual matches to display on stream. Hypernet Arena has been featured by high-profile streamers, such as DrDisRespect.
<br />
<br />
I was one of the core engineers on this project. The game was developed in Unity and built for WebGL. I wrote many components of the gameplay via C#, implementing player movement, gun firing, the damage system, hazards, powerups, networking via Photon, and more. Since the game was built in WebGL, we were limited to 50 MB for the upfront game size. I played a role in optimizing assets to keep the size well below the 50 MB threshold, and I collaborated with our in-house artist to ensure new assets would fit in the game while improving its presentation.
<h2>Showcase</h2>
<div class="grid-container" style="display:grid; grid-template-columns: auto auto auto auto; padding: 10px; grid-gap: 10px 10px; justify-content: space-between">
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Hypernet/gameplay.png' %}">
            <img src="{% static 'pages/images/Hypernet/gameplay.png' %}" width="192" height="120">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Hypernet/train.png' %}">
            <img src="{% static 'pages/images/Hypernet/train.png' %}" width="192" height="120">
        </a>
    </div>
    <div class="grid-item">
        <a target="_self" href="{% static 'pages/images/Hypernet/decoy-powerup.png' %}">
            <img src="{% static 'pages/images/Hypernet/decoy-powerup.png' %}" width="192" height="120">
        </a>
    </div>
</div>

{% endblock %}

personalsite/pages/templates/pages/projects/mathinfection.html
{% extends "pages/project.html" %}

{% load static %}

{% block title %}Math Infection{% endblock %}
{% block ptitle %}Math Infection{% endblock %}
{% block technologies %}C#, XNA, Adobe Photoshop, Git{% endblock %}

{% block pcontent %}

Math Infection is a 2D top-down Shoot 'Em Up designed to help elementary-level students with arithmetic. Each time the player is hit by an enemy or projectile, he/she is required to choose the correct answer to a multiple-choice arithmetic problem. If the answer is correct, the player does not lose health.
<br />
<br />
Math Infection was my final project in an intermediate course at college. The game was built in C# using the XNA framework with a team of four, including me. I implemented player movement and shooting, animations, and created art assets for the HUD, title screen, and player. This was the first project in which I used Git and GitHub.
<br />
<br />
<a target="_blank" href="http://depw.pbworks.com/w/page/49998759/0-Home"><b>Team Blog</b></a>
<br />
<br />

{% endblock %}

personalsite/pages/templates/pages/projects/projects.html
{% extends "pages/default.html" %}

{% load static %}

{% block title %}Projects{% endblock %}

{% block content %}

<font face="Helvetica" color="#555">
    <h2>Projects</h2>
    Here you can find the software projects I've worked on. My free software projects can be found on <a target="_blank" href="https://codeberg.org/kimimaru">Codeberg</a>. Click on any image to be taken to the corresponding project page. Please contact me if you have any questions or feedback.
    <br />
   <!-- <br />
    In addition to these projects, I offer freelance game development services. Please refer to the <a href="/freelancing">freelancing page</a> for more information.
    <br /> -->
    <h2>Professional Experience</h2>
    <div class="grid-container" style="display:grid; grid-template-columns: auto auto auto auto; padding: 30px; grid-gap: 30px 30px; justify-content: start">
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'yousician' %}">
                <img src="{% static 'pages/images/Yousician/yousician-logo.jpg' %}" width="192" height="140">
                <div>
                    <div class="truncate">Yousician</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'onward' %}">
                <img src="{% static 'pages/images/Onward/onward-logo-small.png' %}" width="192" height="140">
                <div>
                    <div class="truncate">Onward</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'hypernet' %}">
                <img src="{% static 'pages/images/Hypernet/coverart.jpg' %}" width="192" height="140">
                <div>
                    <div>Hypernet Arena</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'longbeard' %}">
                <img src="{% static 'pages/images/Longbeard/the-rise-of-captain-longbeard-image.jpg' %}" width="192" height="140">
                <div>
                    <div class="truncate">The Rise of Captain Longbeard</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'blueapprentice' %}">
                <img src="{% static 'pages/images/BlueApprentice/logo.png' %}" width="192" height="140">
                <div>
                    <div class="truncate">Blue Apprentice</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'darblez' %}">
                <img src="{% static 'pages/images/Darblez/darblez.png' %}" width="192" height="140">
                <div>
                    <div class="truncate">Darblez</div>
                </div>
            </a>
        </div>
    </div>

    <h2>Published Projects</h2>
    <div class="grid-container" style="display:grid; grid-template-columns: auto auto auto auto; padding: 30px; grid-gap: 30px 30px; justify-content: start">
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'trbot' %}">
                <img src="{% static 'pages/images/TRBot/TRBotLogo.png' %}" width="192" height="140">
                <div>
                    <div class="truncate">TRBot</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'trbotchatdisplay' %}">
                <img src="{% static 'pages/images/TRBotChatDisplay/TRBotChatDisplayLogo.png' %}" width="192" height="140">
                <div>
                    <div class="truncate">TRBotChatDisplay</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'mazeburrow' %}">
                <img src="{% static 'pages/images/MazeBurrow/MazeBurrow-Title.png' %}" width="192" height="140">
                <div>
                    <div class="truncate">Maze Burrow</div>
                </div>
            </a>
        </div>
    </div>

    <h2>Other Projects</h2>
    <div class="grid-container" style="display:grid; grid-template-columns: auto auto auto auto; padding: 30px; grid-gap: 30px 30px; justify-content: start">
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'pmbs' %}">
                <img src="{% static 'pages/images/PMBS/pmbs-power-lift-screenshot.png' %}" width="192" height="140">
                <div>
                    <div class="truncate">Paper Mario Battle System</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'epicubed' %}">
                <img src="{% static 'pages/images/Epicubed/titlescreen.png' %}" width="192" height="140" class="image">
                <div>
                    <div class="truncate">Epicubed</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'defendyourfort' %}">
                <img src="{% static 'pages/images/DYF/dyftitlescreen.png' %}" width="192" height="140" class="image">
                <div>
                    <div class="truncate">Defend Your Fort</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'smbo' %}">
                <img src="{% static 'pages/images/SMBO/smbo-main-menu.png' %}" width="192" height="140" class="image">
                <div>
                    <div class="truncate">Super Mario Bros. Online</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'streetsofperil' %}">
                <img src="{% static 'pages/images/SoP/statusbonusonhold.png' %}" width="192" height="140" class="image">
                <div>
                    <div class="truncate">Streets of Peril</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'tcfpe' %}">
                <img src="{% static 'pages/images/TCFPE/tcfpetitlescreen.png' %}" width="192" height="140" class="image">
                <div>
                    <div class="truncate">They Came From Planet Earth</div>
                </div>
            </a>
        </div>
        <div class="grid-item">
            <a target="_self" href="{% url 'pages:project' 'mathinfection' %}">
                <img src="{% static 'pages/images/MathInfection/untitled-23.png' %}" width="192" height="140" class="image">
                <div>
                    <div class="truncate">Math Infection</div>
                </div>
            </a>
        </div>
    </div>
</font>

{% endblock %}